steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/genai-src-repo/crbe-preproc-dev:v1'
      - .      
    dir: src/crbe-preproc
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/genai-src-repo/crbe-preproc-dev:v1'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - jobs
      - update
      - crbe-preproc-dev-v1
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/genai-src-repo/crbe-preproc-dev:v1'
      - '--region'
      - us-central1
      - '--service-account'
      - sa-crbe-llm
      - '--cpu'
      - '2'
      - '--memory'
      - 8192Mi
      - '--task-timeout'
      - '1800'
      - '--execute-now'     
    entrypoint: gcloud
options:
  machineType: 'E2_HIGHCPU_32'